version: "3.7"

services:
  discovery-service:
    image: enockwangila1990/library-discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    restart: always
    networks:
      - libra-net

  gateway-service:
    image: enockwangila1990/library-gateway-service
    container_name: gateway-service
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
    ports:
      - '8080:8080'
    restart: always
    networks:
      - libra-net

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=19pool90
      - MYSQL_DATABASE=library
      - MYSQL_PASSWORD=19pool90
    ports:
      - "33061:3306"
    volumes:
      - /home/pathways/Desktop/mydb:/var/lib/mysql
    networks:
      - libra-net

  app-user:
    image: enockwangila1990/library-user-service
    build:
      context: .
    container_name: user-management-service
    depends_on:
      - mysql-db
      - discovery-service
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/library?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
    ports:
      - "8081:8081"
    restart: always
    networks:
      - libra-net

  book-service:
    image: enockwangila1990/library-book-service
    build:
      context: .
    container_name: book-service
    depends_on:
      - mysql-db
      - discovery-service
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/library?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
    ports:
      - '8082:8082'
    restart: always
    networks:
      - libra-net

networks:
  libra-net: