server:
  port: 8082

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/library?createDatabaseIfNotExist=true
    username: root
    password: 19pool90

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

  liquibase:
    change-log: classpath:/db/changelog/liquibase.change-log.xml

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: 'false'

  logging:
    level:
      root: INFO
      com.example.demo_resource_server: DEBUG
      org.springframework.jdbc: DEBUG
      org.springframework.security: trace

openapi:
  service:
    title: book-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    path: /book-service/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: book-service
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true