server:
  servlet:
    context-path: /
  port:
    8081

spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/library?createDatabaseIfNotExist=true
    username: root
    password: 19pool90

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

  liquibase:
    change-log: 'classpath:/db/changelog/liquibase.change-log.xml'


  amqp:
    deserialization:
      trust:
        all: true

openapi:
  service:
    title: user-management-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /user-management-service/v3/api-docs
  swagger-ui:
    path: /user-management-service/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: user-management-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
